version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${databaseUser}
      POSTGRES_PASSWORD: ${databasePassword}
      POSTGRES_DB: ${databaseName}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  app_network:
